language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ashesnz/ashwins-portfolio -f Dockerfile.dev .

script:
  - docker run -e CI=true ashesnz/ashwins-portfolio npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "ashwins-portfolio"
  env: "AshwinsPortfolio-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-311794631399"
  bucket_path: "ashwins-portfolio"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY