language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ashesnz/ashwins-portfolio-test -f Dockerfile.dev .

script:
  - docker run -e CI=true ashesnz/ashwins-portfolio-test npm run test

after_success:
  - docker build -t ashesnz/ashwins-portfolio-web .
  - docker build -t ashesnz/ashwins-portfolio-nginx ./nginx
  - docker build -t ashesnz/ashwins-portfolio-server ./server
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push ashesnz/ashwins-portfolio-web
  - docker push ashesnz/ashwins-portfolio-nginx
  - docker push ashesnz/ashwins-portfolio-server

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "ashwin-portfolio"
  env: "AshwinPortfolio-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-311794631399"
  bucket_path: "ashwins-portfolio"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY