language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ashesnz/ashwins-portfolio -f Dockerfile.dev .

script:
  - docker run -e CI=true ashesnz/ashwins-portfolio npm run test